version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.1.1

setup: &setup
  - run:
      name: Setup
      command: |
        npm install pnpm
        pnpm install

jobs:
  test: # this can be any name you choose
    docker:
      - image: mcr.microsoft.com/playwright:v1.29.2-focal
    resource_class: large
    parallelism: 10

    environment:
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install nodejs 18
          command: |
            apt-get update
            apt-get install -y curl wget gpg
            curl -sL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
      - <<: *setup
      - run:
          name: Install Playwright
          command: |
            pnpm playwright install chromium
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Export and serve
          command: |
            pnpm run export
      - run:
          name: Run tests
          command: |
            pnpm run serve &
            TESTFILES=$(circleci tests glob "specs/e2e/**/*.spec.ts" | circleci tests split --split-by=timings)
            pnpm playwright test --config=playwright.config.ci.ts ${TESTFILES}

  build:
    docker:
      - image: cimg/node:18.12.1
    resource_class: medium
    environment:
      FOLDER: checkout
      NEXT_PUBLIC_DOMAIN: commercelayer.io
      NEXT_PUBLIC_HOSTED: true
    steps:
      - checkout
      - <<: *setup
      - run:
          name: Build
          command: pnpm build
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: out
          to: "s3://$S3_ASSETS_BUCKET/team/fe-static-apps/$FOLDER/<<pipeline.git.tag>>"

workflows:
  # tests:
  #   jobs:
  #     - test:
  #         context: commercelayer
  #         filters:
  #           tags:
  #             ignore: /v.*/

  test-build-and-push:
    jobs:
      # - test:
      #     context: commercelayer
      #     filters:
      #       tags:
      #         only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*/
      #       branches:
      #         ignore: /.*/
      - build:
          # requires:
          #   - test
          context: commercelayer
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*/
            branches:
              ignore: /.*/
